const { today, addCheckin, addBodyRecord, getProfile } = require('../../utils/store')
const { bmi, bodyFat, calorieEstimate } = require('../../utils/metrics')
const { uploadImages, syncCheckin, syncBodyRecord, enabled } = require('../../utils/cloud')
Page({
  data: { activeType:'breakfast', typeOptions:[{key:'breakfast',name:'早餐'},{key:'lunch',name:'午餐'},{key:'dinner',name:'晚餐'},{key:'sport',name:'运动'},{key:'treat',name:'放纵餐'}], portions:[{key:'small',name:'少量'},{key:'normal',name:'正常'},{key:'large',name:'较多'}], portion:'normal', note:'', calories:350, images:[], weight:'' },
  onLoad(){ this.refreshEstimate() }, chooseType(e){ this.setData({activeType:e.currentTarget.dataset.key},()=>this.refreshEstimate()) }, choosePortion(e){ this.setData({portion:e.currentTarget.dataset.key},()=>this.refreshEstimate()) }, refreshEstimate(){ this.setData({calories:calorieEstimate(this.data.activeType,this.data.portion)}) }, input(e){ this.setData({[e.currentTarget.dataset.key]:e.detail.value}) },
  chooseImage(){ wx.chooseMedia({count:3,mediaType:['image'],success:res=>this.setData({images:res.tempFiles.map(f=>f.tempFilePath)})}) },
  async saveCheckin(){ const type=this.data.activeType; if (type === 'sport' && !this.data.note) return wx.showToast({title:'请写下运动内容或时长',icon:'none'}); const record={date:today(),type,portion:this.data.portion,calories:Number(this.data.calories)||0,note:this.data.note,images:this.data.images}; addCheckin(record); this.setData({note:'',images:[]}); if(!enabled()) return wx.showToast({title:'已保存到本地'}); wx.showLoading({title:'正在同步'}); try { record.images=await uploadImages(record.images); await syncCheckin(record); wx.showToast({title:'已保存并同步'}) } catch(error) { console.warn('打卡同步失败',error); wx.showToast({title:'已本地保存，待同步',icon:'none'}) } finally { wx.hideLoading() } },
  async saveWeight(){ const weight=Number(this.data.weight); const p=getProfile(); if(!weight) return wx.showToast({title:'请输入有效体重',icon:'none'}); const bmiValue=bmi(weight,p.height); const record={date:today(),weight,bmi:bmiValue,bodyFat:bodyFat({gender:p.gender,age:p.age,bmiValue})}; addBodyRecord(record); this.setData({weight:''}); if(!enabled()) return wx.showToast({title:'身体数据已更新'}); try { await syncBodyRecord(record); wx.showToast({title:'已更新并同步'}) } catch(error) { console.warn('身体数据同步失败',error); wx.showToast({title:'已本地保存，待同步',icon:'none'}) } }
})
